language: python
sudo: false
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - "pypy"
script:
  - python setup.py test
after_success:
  - coverage report -m
  - pip install coveralls
  - coveralls

